---
# vim: set ts=2 sw=2 et ft=ansible:
- hosts: all
  connection: local
  tasks:
    - name: Fetch YouCompleteMe plugin for vim
      git:
        repo=https://github.com/Valloric/YouCompleteMe.git
        dest=~/YouCompleteMe-demo
        update=yes
        accept_hostkey=yes

